"""Connors Research Dynamic Treasuries strategy package."""

from strategies.ConnorsResearchDynamicTreasuries.core import (
    DYNAMIC_TREASURIES_UNIVERSE,
    TREASURY_ANCHOR,
    TREASURY_DURATION_ASSETS,
    TREASURY_DURATIONS,
    DynamicTreasuriesBacktestResult,
    DynamicTreasuriesConfig,
    backtest_dynamic_treasuries,
    build_rebalance_events,
    compute_asset_performance,
    compute_duration_exposure,
    compute_momentum_returns,
    compute_positive_signal_counts,
    generate_dynamic_treasuries_target_weights,
    generate_live_rebalance_orders,
    load_dynamic_treasuries_prices,
    summarize_rebalances,
    validate_live_readiness,
)

__all__ = [
    "DYNAMIC_TREASURIES_UNIVERSE",
    "TREASURY_ANCHOR",
    "TREASURY_DURATION_ASSETS",
    "TREASURY_DURATIONS",
    "DynamicTreasuriesBacktestResult",
    "DynamicTreasuriesConfig",
    "backtest_dynamic_treasuries",
    "build_rebalance_events",
    "compute_asset_performance",
    "compute_duration_exposure",
    "compute_momentum_returns",
    "compute_positive_signal_counts",
    "generate_dynamic_treasuries_target_weights",
    "generate_live_rebalance_orders",
    "load_dynamic_treasuries_prices",
    "summarize_rebalances",
    "validate_live_readiness",
]
