"""Directional forex ML research strategy."""

from strategies.DirectionalForexML.core import (
    PAPER_FOREX_COSTS,
    USD_BASE_TO_PAPER_SYMBOL,
    DirectionalForexMLArtifact,
    DirectionalForexMLConfig,
    DirectionalForexMLResult,
    FeatureSet,
    ForexCostSpec,
    ModelName,
    apply_ml_probability_gate,
    backtest_directional_forex_ml,
    break_even_move_pct,
    build_directional_labels,
    build_ml_gate_for_signals,
    compute_directional_features,
    cost_spec_for_symbol,
    estimate_expected_move,
    generate_directional_ml_signals,
    invert_usd_base_quote,
    madl_score,
    optimize_probability_threshold,
    predict_directional_probabilities,
    prepare_ml_dataset,
    train_directional_forex_model,
)
from strategies.DirectionalForexML.macro import load_treasury_macro_csv
from strategies.DirectionalForexML.reporting import (
    generate_directional_forex_ml_model_comparison_charts,
    generate_directional_forex_ml_report,
)
from strategies.DirectionalForexML.risk import run_var_backtests
from strategies.DirectionalForexML.research import (
    DirectionalForexMLWalkForwardConfig,
    PAPER_REGIME_PERIODS,
    run_cost_sensitivity,
    run_directional_forex_ml_walk_forward,
    run_future_validation,
    run_regime_period_validation,
    split_walk_forward,
    summarize_walk_forward,
)
from strategies.DirectionalForexML.statistics import (
    bootstrap_confidence_interval,
    paired_return_tests,
    superior_predictive_ability_test,
)

__all__ = [
    "DirectionalForexMLArtifact",
    "DirectionalForexMLConfig",
    "DirectionalForexMLResult",
    "DirectionalForexMLWalkForwardConfig",
    "FeatureSet",
    "ForexCostSpec",
    "ModelName",
    "PAPER_FOREX_COSTS",
    "PAPER_REGIME_PERIODS",
    "USD_BASE_TO_PAPER_SYMBOL",
    "apply_ml_probability_gate",
    "backtest_directional_forex_ml",
    "break_even_move_pct",
    "build_directional_labels",
    "build_ml_gate_for_signals",
    "compute_directional_features",
    "cost_spec_for_symbol",
    "estimate_expected_move",
    "generate_directional_forex_ml_model_comparison_charts",
    "generate_directional_forex_ml_report",
    "generate_directional_ml_signals",
    "invert_usd_base_quote",
    "load_treasury_macro_csv",
    "madl_score",
    "optimize_probability_threshold",
    "paired_return_tests",
    "predict_directional_probabilities",
    "prepare_ml_dataset",
    "bootstrap_confidence_interval",
    "run_cost_sensitivity",
    "run_directional_forex_ml_walk_forward",
    "run_future_validation",
    "run_regime_period_validation",
    "run_var_backtests",
    "split_walk_forward",
    "summarize_walk_forward",
    "superior_predictive_ability_test",
    "train_directional_forex_model",
]
